### ISSUE TITLE
Automate glslang builds & packaging with poetry and `build.py`

### ISSUE THREAD

**Issue by Argmaster** [UniversityOfGdanskTeamPython/pyglslang#2]
To correctly package glslang into wheel and sdist it is necessary to configure project in way understandable for pip and other package managers. You can refer to how [cmake](https://github.com/scikit-build/cmake-python-distributions) PyPI distribution is done or to any other resources out there. As a result a single command (`pip install pyglslang`) should be sufficient to build pyglslang from source on Windows. I assume that this program will be invoked via CLI, so we can just compile it to platform specific executable and copy inside package afterwards to embed it into wheel.

**Comment by MatSzpy** [comment]
I've read the `glslang` documentation which contains a set of rules for preparing and performing installation of it on Linux. Also, I've made the first steps towards installing `glslang` on a remote system, but I've run into a problem with `cmake` which I hope will be resolved soon.

**Comment by MatSzpy** [comment]
Problem with `cmake` was resolved, allowing me to fully install `glslang` on Ubuntu. What's more I have automated process of installing `glslang` builds & packaging using poetry. From now on, I will focus on creating an API for `glslang` and other issues related to it.

**Comment by MatSzpy** [comment]
After establishing what the project of glslang API should look like, I tried writing it in Python. Unfortunately, the current code isn't well-polished yet and requires corrections, so I will try to finish it in the next few days. The code should be ready this week.
